version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the project...
      - dotnet build --configuration Release
      - echo Publishing the project...
      - dotnet publish --configuration Release --output ./publish
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - publish/**/*   # Certifique-se de que todos os arquivos publicados estão incluídos
  discard-paths: yes
