version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  pre_build:
    commands:
      - echo Restoring dependencies...
      - dotnet restore VelorettiAPI/VelorettiAPI.csproj
  build:
    commands:
      - echo Building the project...
      - dotnet build VelorettiAPI/VelorettiAPI.csproj
      - echo Publishing the project...
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ VelorettiAPI/VelorettiAPI.csproj
      - echo Build completed successfully
artifacts:
  files:
    - '**/*' 
